[package]
name = "day02"
version = "0.1.0"
authors = [ "David Kowis <david@kow.is>" ]
edition = "2021"

[dependencies]
shared = { path = "../shared" }
thiserror = "2.0.3"
indoc = "2.0.5"

[dev-dependencies]
pretty_assertions = "1.4.1"